Repository octokit/plugin-retry.js, pull requests merged in 2022-07, with the labels that each got.

#324 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: blocked, maintenance

#329 ci(test): use test_matrix and test jobs
  .github/workflows/test.yml
Labels: maintenance

#332 [deps] updates pika/pack to a non vulnerable version
  package-lock.json
  package.json
Labels: dependencies, maintenance
