Repository octokit/plugin-retry.js, pull requests merged in 2023-06, with the labels that each got.

#430 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  test/octokit.ts
  test/retry.test.ts
  tsconfig.json
Labels: Type: Maintenance

#432 fix(engines): Revert engine back to 16
  package.json
  scripts/build.mjs
Labels: Type: Bug

#433 fix(engines): revert back to node 14
  package.json
  scripts/build.mjs
Labels: Type: Bug

#427 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Breaking change, Type: Maintenance

#437 fix: mark import of `@octokit/request-error` as type
  src/index.ts
Labels: Type: Bug

#440 fix(deps): add `@octokit/request-error` as a runtime dependency
  package-lock.json
  package.json
Labels: Type: Maintenance

#444 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
