Repository octokit/plugin-retry.js, pull requests merged in 2024-02, with the labels that each got.

#515 maint: fix spelling errors
  CONTRIBUTING.md
Labels: Type: Documentation

#517 feat: package is now ESM
  README.md
  package-lock.json
  package.json
  scripts/build.mjs
  scripts/fix-package-json.js
  test/tsconfig.test.json
Labels: Type: Breaking change, Type: Feature

#518 ci(release): remove old script
  .github/workflows/release.yml
Labels: Type: Maintenance

#520 fix: add missing file extension on bottleneck import
  src/wrap-request.ts
Labels: Type: Bug

#523 fix(pkg): add `main` entry point
  scripts/build.mjs
Labels: Type: Bug
